### ISSUE TITLE
API erreur 500

### ISSUE THREAD

**Issue by 2803media** [IGNF/geoportail-urbanisme-dev#14]
Bonjour 
Depuis la migration du site, l'API ne fonctionne plus (erreur 500) 
https://www.geoportail-urbanisme.gouv.fr/api/#/Documents/get-documents 

Avez vous des informations sur son rétablissement? 
Exemple de requête : https://www.geoportail-urbanisme.gouv.fr/api/document?status=document.production&documentFamily=DU&partition=DU_60471 

Merci

**Comment by mborne** [comment]
Bonjour,

Désolé pour ça, un problème avec le paramètre `documentFamily` a été détecté peu après le passage en PRODUCTION... Nous sommes en train de préparer la livraison du correctif.

Il vous est possible d'adapter facilement pour supprimer le filtrage `documentFamily=DU` qui est innutile en présence d'un filtrage par `partition=DU_60471` (https://www.geoportail-urbanisme.gouv.fr/api/document?status=document.production&partition=DU_60471 est fonctionnelle.)?

**Comment by 2803media** [comment]
Super effectivement sans documentFamily cela fonctionne nickel!

Merci @mborne
