### ISSUE TITLE
les téléchargements des documents ne s'achèvent pas.

### ISSUE THREAD

**Issue by manuamador** [IGNF/geoportail-urbanisme-dev#16]
Bonjour,

Depuis le 10 décembre, les téléchargements via les url:
https://www.geoportail-urbanisme.gouv.fr/document/info/?partition=<partition>

se terminent mais les archives téléchargées sont incomplètes !
Par exemple https://www.geoportail-urbanisme.gouv.fr/document/download-by-partition/DU_74250 s'arrête après quelques dizaines de Mo.

Pouvez-vous voir d'où peut venir le problème ? 

merci pour votre aide

**Comment by mborne** [comment]
Bonjour,

Désolé pour l'absence de com. ici mais ce problème a été résolu.

Je ferme.
