### ISSUE TITLE
Téléchargement des données géographiques (PLU)

### ISSUE THREAD

**Issue by maxmodj** [IGNF/geoportail-urbanisme-dev#17]
Bonjour,

Sauf erreur de ma part, les données géographiques des PLU sont accessibles uniquement à travers l'archive complète. Hors cette archive est très lourde du fait des nombreux pdf qu'elle contient. Cela devient très long à télécharger et peu "écolo"... 
Serait-il possible de mettre à disposition le téléchargement des données géographiques que cette archive contient sans les pdf ?
Merci d'avance de la prise en compte de mon message

**Comment by mborne** [comment]
Bonjour,

Il est actuellement possible de télécharger les données géographiques à l'aide du service WFS ( c.f. https://www.geoportail-urbanisme.gouv.fr/services/ ) et des outils tels QuantumGIS ou ogr2ogr.

Pour plus d'information et éventuellement pour suggérer une solution plus "clé en main", je vous invite à passer svp par [le formulaire de contact](https://www.geoportail-urbanisme.gouv.fr/contact/) qui doit normalement être utilisé pour ce type de demande.

Cordialement,
