### ISSUE TITLE
Problème de téléchargement des archives PLU

### ISSUE THREAD

**Issue by 2803media** [IGNF/geoportail-urbanisme-dev#18]
Bonjour les liens de type https://www.geoportail-urbanisme.gouv.fr/document/download-by-partition/DU_22196 ne semblent plus fonctionner cela arrive sur une page 404 à chaque fois

https://www.geoportail-urbanisme.gouv.fr/document/download-by-partition/DU_248900938

Merci pour le retour

**Comment by manuamador** [comment]
Bonjour,
Je l'ai signalé dans leur formulaire.
En python je contourne avec l'id pour refaire l'url du zip:

avec beautifulsoup pour la page _i_ du flux atom:


`

s = requests.Session()
r = s.get('https://www.geoportail-urbanisme.gouv.fr/atom/download-feed?f[t]=&f[s]=&f[dt]=&f[pagination][page]='+str(i))
        statut_code=r.status_code
        if statut_code == 200:
            #print('Page : '+str(i))
            soup = BeautifulSoup(r.text,features="xml")
            liste_brute=soup.find_all('entry')
            if len(liste_brute)>0:
                for l in liste_brute:
                    titre=l.find('summary').text.lstrip('Dataset Feed correspondant au document "').rstrip('"')
                    texte=l.find('inspire_dls:spatial_dataset_identifier_code').text
                    lienid=str(l).split('https://www.geoportail-urbanisme.gouv.fr/api/document/')[1].split('/metadata" rel="describedby"')[0]
                    titre_tab=titre.split('_')
                    comm=titre_tab[0]
                    typededoc=titre_tab[1]
                    if typededoc in ['POS','PLU','CC']:#,'PLUi']:
                        liendoc='https://www.geoportail-urbanisme.gouv.fr/api/document/'+lienid+'/download/'+titre+'.zip'`

**Comment by 2803media** [comment]
Oui je suis entrain de modifier cela avec l'id aussi mais c'est ballot de mettre cette méthode dans la doc si elle ne fonctionne plus ;)

**Comment by mborne** [comment]
@floriancerizay tu pourras faire une passe dans cette documentation pour référencer les méthodes documentées au niveau de l'API : 

https://www.geoportail-urbanisme.gouv.fr/api/

?

PS : Je pense qu'il faut rétablir au moins un temps ces méthodes dépréciées (cette doc n'est pas la seule à les référencer, c.f. SERVICE DE TÉLÉCHARGEMENT PAR PARTITION DU GPU  dans https://www.geoportail-urbanisme.gouv.fr/services/ )
