### ISSUE TITLE
Problème pagination flux ATOM

### ISSUE THREAD

**Issue by 2803media** [IGNF/geoportail-urbanisme-dev#19]
La pagination du flux ne fonctionne plus cela boucle uniquement sur la première page....

![Screenshot 2023-01-05 at 17 35 08](https://user-images.githubusercontent.com/642545/210832461-757cdbe5-0b9c-4463-a4b4-24ca9554e22c.jpg)

![Screenshot 2023-01-05 at 17 34 57](https://user-images.githubusercontent.com/642545/210832451-a93e446e-54ec-424d-9bb7-85f4f07c2242.jpg)

**Comment by 2803media** [comment]
J'ai trouvé le format de l'url a changé mais pas dans la doc... 

https://www.geoportail-urbanisme.gouv.fr/atom/download-feed?f[pagination][page]=2

**Comment by mborne** [comment]
@floriancerizay pour info
