### ISSUE TITLE
Blocage d'IP intempestif sur le serveur

### ISSUE THREAD

**Issue by 2803media** [IGNF/geoportail-urbanisme-dev#2]
Cela est certainement lié à la migration mais je constate que le serveur du site https://www.geoportail-urbanisme.gouv.fr/ à la mauvaise habitude de bloquer les IP ce qui fait que le site est inaccessible au bout d'un certain temps sur l'IP de l'utilisateur. 

Je précise que les accès sont normaux en consultation classique et bloque donc toutes requêtes WFS qui de ce fait qui sont elles aussi bloquées pour l'utilisateur de cette même IP.

Voici l'erreur rencontrée dans chrome:

Ce site est inaccessible Impossible de trouver l'adresse IP du serveur de www.geoportail-urbanisme.gouv.fr.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by manuamador** [comment]
Je n'utilise pas le wfs je travaille sur 3000 communes réparties sur toute la France, j'utilise le rss pour récupérer les fichiers et je mets à jour une couche tous les jours en ajoutant que les nouvelles communes ou les documents mis à jour.

**Comment by mborne** [comment]
@2803media Désolé pour le temps de réponse mais l'erreur DNS_PROBE_FINISHED_NXDOMAIN était probablement liée aux migrations vers la nouvelle infrastructure.

Vous confirmez que vous ne rencontrez plus d'erreur?

**Comment by 2803media** [comment]
Merci effectivement le problème de DNS est réglé maintenant!
