### ISSUE TITLE
Erreur sur le site valeur maximale du WFS

### ISSUE THREAD

**Issue by 2803media** [IGNF/geoportail-urbanisme-dev#20]
Pour information sur cette page https://www.geoportail-urbanisme.gouv.fr/services/

c'est "Attention ! les requêtes sur les flux WFS sont paginées et limitées à 5 000 objets" et non plus 10000 comme avant.... Je viens de passer 2 heures à comprendre pourquoi je n'avais plus que la moitié des PLU, c'est finalement l'explication la plus logique.

![Screenshot 2024-03-18 at 22 44 18](https://github.com/IGNF/geoportail-urbanisme-dev/assets/642545/0a27f00e-3170-4ea6-b5c1-a4cb38a69c48)

**Comment by floriancerizay** [comment]
Merci pour le signalement, c'est corrigé
