### ISSUE TITLE
Le format de sorti n'est pas respecté

### ISSUE THREAD

**Issue by 2803media** [IGNF/geoportail-urbanisme-dev#6]
Depuis aujourd'hui il y a un problème sur le wms exemple:

`https://wxs-gpu.mongeoportail.ign.fr/externe/vkd1evhid6jdj5h4hkhyzjto/wms/v?&service=WMS&request=GetMap&layers=du&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=256&height=256&srs=EPSG%3A3857&bbox=132083.1848767846,5760294.451570883,134529.16978191023,5762740.43647601`

qui donne un xml au lieu de l'image png avec ce message d'erreur:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE ServiceExceptionReport SYSTEM "http://geoserver-externe-gpu.mongeoportail.ign.fr:80/geoserver/schemas/wms/1.1.1/WMS_exception_1_1_1.dtd"> <ServiceExceptionReport version="1.1.1" >   <ServiceException>
      Internal error
featureType: du:du_bdd_production_v1-zone_urba does not have a properly configured datastore
</ServiceException></ServiceExceptionReport>
```

**Comment by 2803media** [comment]
incident réglé apparement

**Comment by mborne** [comment]
Bonjour,

Merci pour l'alerte et désolé pour le temps de réponse, il y a effectivement eu des instabilités hier et l'un des geoserver semblait en vrac.

J'attendais de voir si le redémarrage nocturne résolvait le problème ce qui semble être le cas...

**Comment by 2803media** [comment]
Bonjour @mborne vous êtes en maintenance aujourd'hui cela n'a pas l'air de fonctionner?

Merci par avance

**Comment by mborne** [comment]
Bonjour, il y a effectivement des problèmes d'infra : 

https://geoservices.ign.fr/blog/2019/11/28/Indispo_services_geopo.html

Désolé pour ces soucis...

**Comment by 2803media** [comment]
Merci pour le lien!
